"""empty message

Revision ID: 48ff724146a0
Revises: 15f4f02a8378
Create Date: 2025-05-08 10:26:00.037475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48ff724146a0'
down_revision = '15f4f02a8378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.drop_column('age_years')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('registraion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registraion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('registration_date')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_years', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
